apiVersion: v1
kind: Namespace
metadata:
  name: ns-posthub--env
  labels:
    name: ns-posthub--env

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui--env
  namespace: ns-posthub--env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui--env
  template:
    metadata:
      labels:
        app: ui--env
    spec:
      containers:
        - name: ui--env
          image: acr12601.azurecr.io/alissonpmedeiros/users:v1.0
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              memory: "128M"
              cpu: "250m"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service--env
  namespace: ns-posthub--env
spec:
  selector:
    app: ui--env
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: ui--env